USE capco_hcm;
CREATE TABLE EMPLOYEE_BAND_TRACKER (
	Emp_Id INT, 
	Hired_Band CHAR(2), 
	Manager_Cit VARCHAR(100), 
	Manager_Ps VARCHAR(100),
	Team_Lead_Ps VARCHAR(100),
	Insertion_Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	Inserted_By VARCHAR(100),
	FOREIGN KEY (Emp_Id)
		REFERENCES EMP_INFO(Emp_Id)
		ON UPDATE CASCADE ON DELETE RESTRICT
);

USE capco_hcm;
CREATE TABLE REVIEW_CYCLE_TRACKER (
	Emp_Id INT,
	Review_Cycle VARCHAR(10),
	Review_Band CHAR(2),
	Insertion_Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	FOREIGN KEY (Emp_Id)
		REFERENCES EMPLOYEE_BAND_TRACKER(Emp_Id)
		ON UPDATE CASCADE ON DELETE RESTRICT
);