use capco_hcm;
CREATE TABLE DOC_BGV_TRACKER (
	Emp_Id INT, 
	Pre_Onboarding_Initiated BOOLEAN,
	Owner VARCHAR(100),
	Welcome_Email_Date DATE,
	Document_Received_Date DATE,
	First_Chaser DATE,
	Second_Chaser DATE,
	Third_Chaser DATE,
	Escalation_Date DATE,
	Nhp_Creation_Date DATE,
	New_Hire_Provision VARCHAR(256),
	Signed_Offer_Letter BOOLEAN,
	Cv BOOLEAN,
	Personal_Details_Form BOOLEAN,
	Mediclaim_Nomination_Form BOOLEAN,
	PF_Nomination_Form BOOLEAN,
	Passport_Size_Photo BOOLEAN,
	Nda BOOLEAN,
	Code_Of_Conduct BOOLEAN,
	Releiving_Letter BOOLEAN,
	Experience_Letter BOOLEAN,
	Last_Payslips BOOLEAN,
	Marksheets BOOLEAN,
	Pan_Card VARCHAR(10),
	Passport_Number VARCHAR(10),
	Passport_Expire DATE,
	Types_Of_Visa VARCHAR(256),
	Visa_Country VARCHAR(256),
	Bgv_Initiated_Date DATE,
	Bgv_Ref_Number VARCHAR(20),
	Bgv_Interim_Report DATE,
	Bgv_Final_Report DATE,
	Bgv_Color_Code CHAR(1),
	Bgv_Sign_Off_By VARCHAR(100),
	Bgv_Sign_Off_Date DATE,
	Bgv_Closure_Date DATE,
	Package_Initiated VARCHAR(80),
	Employment VARCHAR(30),
	Court_Check VARCHAR(30),
	Identity_Check VARCHAR(30),
	Country_Check VARCHAR(30),
	Reference_Check VARCHAR(30),
	Cv_Check VARCHAR(30),
	Deleted BOOLEAN,
	Insertion_Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	Inserted_By VARCHAR(100),
	FOREIGN KEY (Emp_Id)
		REFERENCES EMP_INFO(Emp_Id)
		ON UPDATE CASCADE ON DELETE RESTRICT	
);