USE capco_hcm;
CREATE TABLE EMP_INFO (
	Emp_Id INT, 
	Emp_Name VARCHAR(100), 
	Sec_Emp_Id VARCHAR(10), 
	File_No VARCHAR(20), 
	Date_Of_Birth DATE, 
	Joining_Date DATE, 
	Emp_Status CHAR(1), 
	Gender BOOLEAN, 
	HcBp VARCHAR(100), 
	Capco_Login_Id VARCHAR(5), 
	Designation CHAR(2), 
	Atp BOOLEAN, 
	Service CHAR(1), 
	Project VARCHAR(30),
	Type_Of_Employment VARCHAR(15),
	Billing_Status BOOLEAN, 
	Fte_Contractor BOOLEAN,  
	Start_Date DATE, 
	Official_Email_Id VARCHAR(100),
	Personal_Email_Id VARCHAR(100), 
	Contact_Number VARCHAR(15), 
	House CHAR(1), 
	Deleted BOOLEAN,
	Insertion_Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	Inserted_By VARCHAR(100),
	PRIMARY KEY(Emp_Id)
);