use capco_hcm;
CREATE TABLE ENDORSEMENT_TRACKER (
	Emp_Id INT, 
	GPA_Sum_Assured VARCHAR(15),
	GTL_Sum_Insured VARCHAR(15),
	GMC_Sum_Insured VARCHAR(15),
	Annual_Ctc VARCHAR(15),
	Deleted BOOLEAN,
	Insertion_Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	Inserted_By VARCHAR(100),
	FOREIGN KEY (Emp_Id)
		REFERENCES EMP_INFO(Emp_Id)
		ON UPDATE CASCADE ON DELETE RESTRICT	
);

use capco_hcm;
CREATE TABLE NOMINATION_DETAILS (
	Emp_Id INT, 
	Deleted BOOLEAN,
	Dependent_Name VARCHAR(100),
	Relation VARCHAR(20),
 	Gender boolean,
	Nominee_Date_Of_Birth DATE,
	Nominee_Age VARCHAR(3),
	EmailId VARCHAR(100),
	Insertion_Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	Inserted_By VARCHAR(100),
	FOREIGN KEY (Emp_Id) 
		REFERENCES ENDORSEMENT_TRACKER(Emp_Id)
		ON UPDATE CASCADE ON DELETE RESTRICT
);