USE capco_hcm;

INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('PROJECT', 'PROJECT', 'CATEGORY', FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('DESIGNATION', 'DESIGNATION', 'CATEGORY', FALSE);

INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Managing Partner', 'MPR', 'DESIGNATION', FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Partner', 'PAT', 'DESIGNATION', FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Administrator', 'ADM', 'DESIGNATION', FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Analyst', 'ANA', 'DESIGNATION', FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Associate', 'ASO', 'DESIGNATION', FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Consultant1', 'CO1', 'DESIGNATION', FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Consultant2', 'CO2', 'DESIGNATION', FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Contractor', 'CON', 'DESIGNATION', FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Manager', 'MGR', 'DESIGNATION', FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Managing Principal', 'MNP', 'DESIGNATION', FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Principal Consultant1', 'PC1', 'DESIGNATION', FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Principal Consultant2', 'PC2', 'DESIGNATION', FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Senior Analyst', 'SRA', 'DESIGNATION', FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Senior Consultant1', 'SC1', 'DESIGNATION', FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Senior Consultant2', 'SC2', 'DESIGNATION', FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Sourcing Analyst', 'SCA', 'DESIGNATION', FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Specialist', 'SPL', 'DESIGNATION', FALSE);

INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Finance','FIN','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('HSBC - Athena','HSBC_ATHENA','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('MS','MS','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Credit Suisse','CS','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Imago - Fx','IMG_FX','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Recruitment','RECRUIT','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Imago - Credit Dev','IMG_CREDIT_DEV','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Imago - Functional Support','IMG_FS','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('MS CoE','MS_COE','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('HSBC - GTC','HSBC_GTC','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Jefferies','JEFF','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('TD','TD','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Imago - Technical Support','IMG_TS','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('SBI','SBI','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Capco North America','CAP_NA','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Jefferies-Murex','JEFF_MX','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Imago - Card Dev','IMG_CARD_DEV','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('HC - BP','HCBP','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('HSBC - UK offshore','HSBC_UK_OFF','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('HSBC - Appway','HSBC_APWY','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('IT - Local Team','IT_LCL','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('KM Team','KM','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Bench','BEN','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Imago - Card Support','IMG_CARD_SUPP','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('HSBC -  US offshore','HSBC_US_OFF','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('DZ Bank','DZ','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('HSBC - KYC Remediation','HSBC_KYC_REM','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Admin','ADM','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Digital - HK','DIG_HK','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Fin - Ops','FIN_OPS','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('GSD','GSD','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('India Management','IND_MNG','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Imago - FX Tester','IMG_FX_TST','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Imago - PMO','IMG_PMO','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Imago - Credit BA','IMG_CRD_BA','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Quality','QA','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Imago - Card Tester','IMG_CARD_TST','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Imago - EAI','IMG_EAI','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('VARMA','VARMA','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('IT - APAC','IT_APAC','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('SS - APAC','SS_APAC','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Imago - Card','IMG_CARD','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Finance - APAC','FIN_APAC','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('Finance - Global','FIN_GLBL','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('SS - Recruitment','SS_RECRUIT','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('HSBC - UK Retail','HSBC_UK_RTL','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('SS - India','SS_IND','PROJECT',FALSE);
INSERT INTO HCM_STATIC_TABLE (Field_Name, Field_Key, Field_Category, DELETED) VALUES ('DigitalINBA','DIG_INBA','PROJECT',FALSE);